### PR TITLE
Check for Lucky Number in Java

### PR DESCRIPTION
**Pull request by srijanishere**
## Program in Java to accept a number from the user and check if it is a Lucky Number or not
<b>Lucky Number</b> : The sequence of natural numbers or subset of integers that we get after removing second, third, fourth, fifth, and so on number respectively from the sequence. By applying the process there still remains some numbers indefinitely in the sequence such numbers are known as lucky numbers.

### CODE REVIEW

**Review by PrajaktaSathe — CHANGES_REQUESTED** [review]
No need to include LuckyNumber.class
You can go ahead and remove that.

**Comment by srijanishere** [comment]
Deleted the LuckyNumber.class file as requested.

**Review by PrajaktaSathe — APPROVED** [review]

**Comment by PrajaktaSathe** [comment]
Also, update the main readme file with your program details. Thanks!

**Comment by srijanishere** [comment]
Will do

**Comment by srijanishere** [comment]
@PrajaktaSathe Should I open a new PR to update the readme file?

**Comment by PrajaktaSathe** [comment]
Yes

**Comment by srijanishere** [comment]
Done, please check.

**Pull request merged**
