### PR TITLE
Code added for multiplication of two matrix

### PR DESCRIPTION
**Pull request by siddhant2002**

### CODE REVIEW

**Comment by siddhant2002** [comment]
I've added java code for multiplication of 2 matrix. Please check the pr

**Review by PrajaktaSathe — APPROVED** [review]

**Comment by PrajaktaSathe** [comment]
Could you add your program name and description to the main readme file, so that I can merge the PR?

**Comment by siddhant2002** [comment]
I've updated the README file. Thanks.

**Comment by PrajaktaSathe** [comment]
Thank you for contributing! Do star the repo!

**Pull request merged**
